#!/usr/bin/env python3
"""CLI utility to create an enrichment job, poll for completion, and print results."""

from __future__ import annotations

import argparse
import json
import os
import sys
from uuid import uuid4

from masleads_client import MasLeadsClient, MasLeadsError


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Enrich a LinkedIn profile with verified email or phone via MasLeads API"
    )
    parser.add_argument(
        "--linkedin",
        required=True,
        help="Target LinkedIn profile URL (e.g., https://www.linkedin.com/in/username)",
    )
    parser.add_argument(
        "--field",
        choices=("email", "phone"),
        required=True,
        help="Contact field to discover ('email' or 'phone')",
    )
    parser.add_argument(
        "--external-id",
        dest="external_id",
        help="Optional external tracking ID (e.g., CRM lead ID)",
    )
    parser.add_argument(
        "--idempotency-key",
        dest="idempotency_key",
        help="Unique idempotency key (defaults to autogenerated UUID)",
    )
    args = parser.parse_args()

    api_key = os.environ.get("MASLEADS_API_KEY", "").strip()
    if not api_key:
        sys.exit("Error: MASLEADS_API_KEY environment variable is missing or empty.")

    client = MasLeadsClient(api_key=api_key)

    try:
        usage = client.usage()
        print(f"Account: {usage.get('plan_name', 'Standard')} | Credits remaining: {usage.get('credits_available', 'unknown')}")

        idempotency_key = args.idempotency_key or f"python-{uuid4()}"
        print(f"Submitting job with Idempotency-Key: {idempotency_key} ...")

        created = client.create_job(
            linkedin_url=args.linkedin,
            field=args.field,
            idempotency_key=idempotency_key,
            external_id=args.external_id,
        )
        job_id = created["job_id"]
        print(f"Job created successfully: {job_id}")

        final_job = client.wait(job_id=job_id, poll_interval=15)
        status = final_job.get("status")

        if status == "completed":
            print("\nEnrichment results:")
            results = client.results(job_id)
            print(json.dumps(results, indent=2, ensure_ascii=False))
        elif status == "blocked":
            blocker = final_job.get("blocker") or {}
            reason = blocker.get("message") or blocker.get("code") or "Job blocked"
            sys.exit(f"Job was blocked by MasLeads: {reason}")
        else:
            sys.exit(f"Job finished with unexpected terminal status: {status}")

    except MasLeadsError as err:
        sys.exit(f"API Error: {err}")
    except TimeoutError as err:
        sys.exit(f"Timeout Error: {err}")


if __name__ == "__main__":
    main()
